server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: moderator-service
  config:
    import: ${CONFIG_IMPORT:configserver:http://localhost:8888}
  profiles:
    include:
      - db
      - kafka
      - metric
      - log
      - eureka
      - trace
      - security
      - feign
      - mailsender


